#!/usr/bin/env python3
"""Generate the Pygments stylesheets for the Ulwazi theme.

Sphinx's built-in syntax highlighting emits a single stylesheet from
``pygments_style`` (light) and, if ``pygments_dark_style`` is set, a second
one wrapped in a ``@media (prefers-color-scheme: dark)`` block. That media
query follows the browser/OS preference, not the theme's class-based toggle
(``body.is-dark`` + localStorage), so the two would disagree.

This script instead generates BOTH palettes as static stylesheets scoped to
the theme's toggle classes:

- ``pygments-light.css`` -- scoped to ``body.is-light``
- ``pygments-dark.css``  -- scoped to ``body.is-dark``

Background rules are stripped from both: the code-block surface is owned by
the theme's ``--vf-color-background-code`` Vanilla token (see
``_ulwazi.scss``), and an opaque Pygments background would paint over it.

Run manually when a style or the token set needs updating:

    python3 ulwazi/theme/ulwazi/static/css/generate_pygments_css.py

The output is committed as ``pygments-light.css`` and ``pygments-dark.css``
next to this script.
"""

from __future__ import annotations

from pathlib import Path
from typing import cast

from pygments.formatters.html import HtmlFormatter

# (output file name, Pygments style name, theme class to scope under)
STYLES: list[tuple[str, str, str]] = [
    ("pygments-light.css", "autumn", "body.is-light"),
    ("pygments-dark.css", "github-dark", "body.is-dark"),
]

# Rules that set an opaque background on the code-block surface. The theme
# owns the surface color via --vf-color-background-code; keeping these would
# paint an opaque background over it.
DROP_PREFIXES = (
    ".highlight {",  # sets background + default text color
    "pre {",  # line-height only, but scoped to nothing useful
    "td.linenos .normal {",
    "span.linenos {",
    "td.linenos .special {",
    "span.linenos.special {",
)


def generate(style: str, scope: str) -> str:
    """Return the Pygments CSS for ``style``, scoped under ``scope``."""
    # HtmlFormatter is generic over the write type; the types-Pygments stubs
    # leave get_style_defs() unannotated, so cast to keep pyright strict happy.
    formatter = HtmlFormatter[str](style=style)
    css = cast(
        "str",
        formatter.get_style_defs(".highlight"),  # pyright: ignore[reportUnknownMemberType, reportUnknownArgumentType]  # stub is unannotated
    )

    lines: list[str] = [
        "/*",
        " * Syntax highlighting for the Ulwazi theme.",
        " *",
        " * Generated by generate_pygments_css.py -- do not edit by hand.",
        f" * Pygments style: {style}.",
        " *",
        f" * Scoped to {scope} so it follows the theme toggle.",
        " * Background rules are stripped: the code-block surface is owned by",
        " * --vf-color-background-code (see _ulwazi.scss).",
        " */",
    ]

    for line in css.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if any(stripped.startswith(prefix) for prefix in DROP_PREFIXES):
            continue
        # Rules look like ".highlight .k { color: #00A }".
        lines.append(f"{scope} {stripped}")

    return "\n".join(lines) + "\n"


def main() -> None:
    """Write each generated stylesheet next to this script."""
    for filename, style, scope in STYLES:
        out_path = Path(__file__).parent / filename
        out_path.write_text(generate(style, scope), encoding="utf-8")
        print(f"Wrote {out_path} (style: {style})")


if __name__ == "__main__":
    main()
