[tox]
envlist = build-css, build-docs, validate-html, validate-scss
isolated_build = True
skipsdist = True

[testenv:build-css]
description = Build CSS from SCSS (vanilla-main)
deps =
allowlist_externals = make
commands =
    make vanilla-main

[testenv:build-docs]
description = Build Sphinx docs using the theme
deps =
    sphinx
allowlist_externals = make
commands =
    make html

[testenv:validate-html]
description = Validate docs/_build/index.html for broken assets
deps =
    pytest
    beautifulsoup4
    lxml
allowlist_externals = make
commands =
    pytest -s tests/test_site_validation.py

[testenv:validate-scss]
description = Validate scss properties propagation to
deps =
    pytest
    beautifulsoup4
    lxml
    playwright
allowlist_externals = 
    make
    playwright
commands =
    playwright install chromium
    pytest -s tests/scss_propagation.py