[theme]
inherit = "basic-ng"
stylesheets = [
    "css/vanilla-main.css",
    "css/default.css",
    "css/skeleton.css",
    "css/feedback.css",
    "css/sidenav.css",
    "css/tasklist.css",
    "css/local-toc.css",
    "css/search.css",
    "css/vanilla-main.css",
]
sidebars = [
    "globaltoc.html",
]

[options]
globaltoc_collapse = "true"
globaltoc_maxdepth = "3"