name: Run make test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install PDF dependencies
        run: sudo make pdf-prep-force

      - name: Build SCSS
        run: make vanilla-main

      - name: Build HTML
        run: make html

      - name: Build PDF
        run: make pdf

      - name: Run tests
        run: make test
